### ISSUE TITLE
The sender of the event is not TwitchClient

### ISSUE THREAD

**Issue by DarkoreXOR** [TwitchLib/TwitchLib.Client#11]
```C#
private void _client_OnError(object sender, ErrorEventArgs e)
{
    OnConnectionError?.Invoke(_client, new OnConnectionErrorArgs { BotUsername = TwitchUsername, Error = new ErrorEvent { Exception = e.Exception, Message = e.Exception.Message } });
    Reconnect();
}
```
Why is the event sender == _client (may be it should be "this")?

**Comment by Syzuna** [comment]
Hi,

the sender is _client beacause in fact thats an event from the Websocket client not the TwitchClient class

**Comment by DarkoreXOR** [comment]
The problem is that I inherit the class from TwitchClient, in which I use the Context property and when some events send the sender of the TwitchClient, and some other internal TwitchClient objects with which I do not even work. Therefore, I can not get the context in the end. And it breaks everything. I believe that the sender of the event should be the one with whom we work in our code, namely TwitchClient. We do not need to know from what parts it consists and take events from them.

**Comment by Syzuna** [comment]
I see where you are coming from and it yeah I can see why its breaking your way of working with the client. Lets wait about what swifty says about this once he is awake bcs of timezones :D

**Comment by LuckyNoS7evin** [comment]
@Syzuna I think @DarkoreXOR is right on this one, I've not use these events but would expect it to be a TwitchClient as the Websocket client is internal and doesn't need to be exposed

**Comment by swiftyspiffy** [comment]
I agree with you guys, I think this was an event I forgot to move from_client to "this" when I changed all of the events several months ago. Will get a fix out for this.

**Comment by DarkoreXOR** [comment]
Thank you, now it's what I need.
