### ISSUE TITLE
OnCommunitySubcriptionArgs isn't derived from EventArgs

### ISSUE THREAD

**Issue by Shaky-Wombat** [TwitchLib/TwitchLib.Client#111]
I notice that this is the only class of client event arguments that doesn't derive from EventArgs. It may be deliberate, but it does seem strange.

**Comment by swiftyspiffy** [comment]
Checking.

**Comment by swiftyspiffy** [comment]
Confirmed. Fixed here: https://github.com/TwitchLib/TwitchLib.Client/commit/af502bcaa2fcfc33ae9f66c3ef0b24fe59d0d509

Thanks.
