### ISSUE TITLE
Crashes durring bit wars

### ISSUE THREAD

**Issue by JSpruill-LDS** [TwitchLib/TwitchLib.Client#115]
in my app, i call "client = New TwitchClient()" in its own thread to keep the UI fluid, but i am finding that when bit wars (gifts) go on between viewers, the thread terminates. I am now running source code compiled in debug to see if i can catch the error in the dll. but from the vb.net side i don't see any feedback upon termination.

test case, multiple gifts in a single chat (5+)

Also, i do not see any gift or bit received events, this would be helpful to trigger sounds, text, or other actions based on gifts.

**Comment by swiftyspiffy** [comment]
@JSpruill-LDS can you  update to the latest stable version and see if you're still encountering this problem.

Also sorry for the delay.

**Comment by swiftyspiffy** [comment]
Going to close this. Feel free to reopen if you're still encountering the problem. :)
