### ISSUE TITLE
Client stops listening to chat after raid or sub

### ISSUE THREAD

**Issue by aaron-mulder** [TwitchLib/TwitchLib.Client#116]
I have a simple bot that runs some trivia, however whenever a raid or sub comes in the client discontinues any listening to the chat and must be restarted.

**Comment by Mahsaap** [comment]
Fixed in dev. Install package with pre release checked individually in nuget

**Comment by aaron-mulder** [comment]
Thanks!

**Comment by swiftyspiffy** [comment]
This is now in the stable release. Feel free to reopen this if needed.
