### ISSUE TITLE
Hosting started/stopped event stops working after a while

### ISSUE THREAD

**Issue by JayJay1989** [TwitchLib/TwitchLib.Client#117]
As of a couple of days ago, hosting started/stopped events stopped working after some time (4-7 mins). 
At startup of the 'twitchlib.client' and registering events, it shows all the hosts, after those there will no new hosting messages.
There are no exceptions/errors while this happens.

versions:
TwitchLib.Client 3.0.6-CI-20190707-175305
TwitchLib.Api 3.06-CI-20190707-175300

**Comment by Mahsaap** [comment]
If your not using pre release that will happen atm. Not I think swift is trying to push master here soon

**Comment by JayJay1989** [comment]
Updated now to latest pre release.
