### ISSUE TITLE
Reconnecting after disconnect 

### ISSUE THREAD

**Issue by Bregann** [TwitchLib/TwitchLib.Client#119]
Hey, my bot has been disconnecting quite a bit recently and is firing the OnDisconnected event but I can't work out exactly how to reconnect to it

Tried with Client.Reconnect(); in the OnDisconnected event but didn't  seem to reconnect back to the channel and the OnReconnected event doesn't fire

Any ideas please? 

Thanks

**Comment by Bregann** [comment]
So I've been playing about a bit by manually disconnecting the bot and the OnReconnect keeps firing the OnDisconnect event

**Comment by Bregann** [comment]
What I am now doing on the OnDisconnected event is this
            Client.Connect();
            Thread.Sleep(5000);
            Client.JoinChannel(StartService.ChannelName);

Which bans and messages will alert fine but when trying to send any message or do any commands, it will say it needs to be connected to a channel even though it is connected

**Comment by swiftyspiffy** [comment]
For the time being, I think a connect + a join channel in the OnConnected event should suffice for what you're trying to do.

Do you know if you're being connected by Twitch, because of inconsistent networking, or because of something in the library?

**Comment by Bregann** [comment]
> For the time being, I think a connect + a join channel in the OnConnected event should suffice for what you're trying to do.
> 
> Do you know if you're being connected by Twitch, because of inconsistent networking, or because of something in the library?

Awesome thanks - managed to get it working 👍 

I think it could be inconsistent networking as I haven't been able to work out a pattern and it also just happens at random times when the bot isnt even in use
