### ISSUE TITLE
User data context

### ISSUE THREAD

**Issue by DarkoreXOR** [TwitchLib/TwitchLib.Client#12]
Can you add a custom context object property? I need to work with some data in the TwitchClient event handlers (there can be a lot of clients with the single event handler in code), which I'll get somehow like this:

```C#
var ctx = ((TwitchClient) sender).Context;
// work with context here
```

**Comment by Syzuna** [comment]
I cant rly think of what you mean with a custom context object? what should it contain?

**Comment by DarkoreXOR** [comment]
This should contain just any object of an external user class in which you can write something to associate the TwitchClient with some additional user data. This is very useful when there are so many clients and we need to somehow link one of the TwitchClient with a set of external data and work with the data. The context will be immediately contained in the TwitchClient and will not need to bind external data to the TwitchClient.

**Comment by swiftyspiffy** [comment]
Ya, I don't see why we can't add this.

**Comment by swiftyspiffy** [comment]
@DarkoreXOR Check to see if that's what you mean^

**Comment by swiftyspiffy** [comment]
So after having second thoughts, I went ahead and reverted it. I think this kind of thing should be implemented in your extended client, and not the client itself.

**Comment by DarkoreXOR** [comment]
This was not the main goal, but rather a small wish. Yes, and I decided it in this way. But anyway, thanks for the help.
