### ISSUE TITLE
Streamer stops streaming notification

### ISSUE THREAD

**Issue by sushivap** [TwitchLib/TwitchLib.Client#120]
I'm using TwtichLib to listen to chat after connecting to a channel and this works. But I'd like to get a notification when the streamer stops streaming. I've tried using OnChannelStateChanged, OnHostingStopped and OnHostLeft but none of these fire when the streamer stops streaming.

Am I using the right callbacks and if so what is the correct usage? If not which should I be using?

**Comment by Mahsaap** [comment]
Api live monitor , pubsub or websockets need to be used.

**Comment by sushivap** [comment]
@Mahsaap thanks for the response.

What exactly does OnChannelStateChanged trigger for then?

**Comment by Mahsaap** [comment]
Anything in the channelstate object changes https://github.com/TwitchLib/TwitchLib.Client/blob/dev/TwitchLib.Client.Models/ChannelState.cs

**Comment by sushivap** [comment]
Got it, thank you.
