### ISSUE TITLE
SubscribedMonthCount incorrect

### ISSUE THREAD

**Issue by JayDee23** [TwitchLib/TwitchLib.Client#127]
The SubscribedMonthCount does not contain the correct amount. 
For myself it shows 24 instead of 28. 

The Reason might be this code:

`                        foreach (var badge in Badges)
                        {
                            switch (badge.Key)
                            {
                                case "bits":
                                    CheerBadge = new CheerBadge(int.Parse(badge.Value));
                                    break;
                                case "subscriber":
                                    SubscribedMonthCount = int.Parse(badge.Value);
                                    break;
                            }
                        }`

Looking in the rawIRC-Message shows following:
@badge-info=subscriber/28;badges=broadcaster/1,subscriber/24;color=#1E90FF;display-name=......

I guess you are using the Index (24) out of the badges-part, instead of the badge_info, which states the correct amount of 28.   A bit confusing, but I think this would be the solution. 

The 24 stands for "Two-Year-Subscriber", but the 28 are the total months.

**Comment by swiftyspiffy** [comment]
Yup, you’re probably right. Will look into this in like 10 hours.

**Comment by JayDee23** [comment]
I guess this would be the right time to leave a big THANK YOU for this great library. 
Wrote my own small private bot with individual greetings and some other features belonging to my channel like a poem-command.

**Comment by Mahsaap** [comment]
I dont see that code snippet. What file is that In

**Comment by JayDee23** [comment]
ChatMessage.cs  

https://github.com/TwitchLib/TwitchLib.Client/blob/master/TwitchLib.Client.Models/ChatMessage.cs
I don't know exactly if this is the latest version, I just googled twitchlib and the Property. 

Nvm, read the last sentence too late :)

**Comment by adepierre** [comment]
Just leaving this here for completeness: in case of a founder subscriber, the badge-info is not subscriber/month_count but founder/month_count, so both should be checked

**Comment by swiftyspiffy** [comment]
Sorry for the delay on this, have been busy.

Good callout @adepierre , I believe that is the root problem. See #133

**Comment by adepierre** [comment]
I think that #133 fixes #129 but only partially this issue (for founder subscribers). For regular subscribers, SubscribedMonthCount is still parsed from the badge value (which can only be 1, 3, 6, 12, 24 etc...) while it should parse the badge-info which contains the more accurate month count.

**Comment by swiftyspiffy** [comment]
@adepierre You're right. Cutting new PR to fix the issue completely.

**Comment by swiftyspiffy** [comment]
Should be resolved with this commit: https://github.com/TwitchLib/TwitchLib.Client/commit/1182914de6b23cf4f7295f4e7e72a22eb2c5253b

Feel free to reopen as needed.
