### ISSUE TITLE
Gracefully handle whisper_restricted

### ISSUE THREAD

**Issue by swiftyspiffy** [TwitchLib/TwitchLib.Client#128]
`whisper_restricted` is a `NOTICE` type message from Twitch that indicates whisper settings restrict sending of whispers in some way.

Specifically, the IRC message is:
```
@msg-id=whisper_restricted;target-user-id=56570810 :tmi.twitch.tv NOTICE #jtv :Your settings prevent you from sending this whisper.
```

**Comment by Syzuna** [comment]
most likely wont fix/add this in the current version.
should definetly be included in v4/the rewrite

**Comment by Syzuna** [comment]
Whispers arent done via IRC anymore. This issue is irrelevant now
