### ISSUE TITLE
Gracefully handle VIP user detection

### ISSUE THREAD

**Issue by davidfinzel** [TwitchLib/TwitchLib.Client#130]
Raw IRC message logs indicate that VIP badges are shown in the IRC message, and since they are a slot 1 (exclusive, non-hideable) badge, they should be parsed, and exposed via ChatMessage as a property.

VIPExt is pretty crap, if we're being honest. This is a much simpler way to check a VIP user.

perhaps `.IsVIP` similar to `.IsBroadcaster` etc

```
RAW MESSAGE: @badge-info=;badges=vip/1;color=;display-name=heph2;emotes=;flags=;id=27b2f778-6651-4efd-96ee-22cc23269b54;mod=0;room-id=29181352;subscriber=0;tmi-sent-ts=1573999776196;turbo=0;user-id=64525781;user-type= :heph2!heph2@heph2.tmi.twitch.tv PRIVMSG #heph :a s d f 1 2 3 4
```

^ VIP chat message shown above.

**Comment by swiftyspiffy** [comment]
This has been merged in. Closing. Feel free to reopen as needed.
