### ISSUE TITLE
Gracefully handle a user not able to receive a whisper

### ISSUE THREAD

**Issue by swiftyspiffy** [TwitchLib/TwitchLib.Client#134]
Irc message for when a user is unable to receive a whisper from the client:
```
@msg-id=whisper_restricted_recipient;target-user-id=187514468 :tmi.twitch.tv NOTICE #jtv :That user's settings prevent them from receiving this whisper.
```

**Comment by Syzuna** [comment]
most likely wont fix/add this in the current version.
should definetly be included in v4/the rewrite

**Comment by Syzuna** [comment]
Whispers arent done via IRC anymore. This issue is irrelevant now
