### ISSUE TITLE
OnUserBanned.BanReason empty / not parsed properly

### ISSUE THREAD

**Issue by hephdotdev** [TwitchLib/TwitchLib.Client#139]
Chat output: https://i.imgur.com/VIKoRpK.png
Console logging output: https://i.imgur.com/x11WP2F.png
Code: https://i.imgur.com/Z2Whfgl.png

Not sure why the banreason isn't being populated.
But I noticed it wasn't being reflected in the parsing logic and subsequent UserBan object

TwitchLib.Client version `3.0.6-CI-20191221-060158`

**Comment by Bappsack** [comment]
can confirm.

**Comment by davidfinzel** [comment]
OnUserTimedOut is also effected.
BanReason is always null/empty.

**Comment by teraa** [comment]
Twitch no longer sends that data over IRC, only via PubSub.

**Comment by davidfinzel** [comment]
According to the documentation, that is incorrect.
https://dev.twitch.tv/docs/irc/tags#clearchat-twitch-tags

Still sent on timeouts, bans, and purges.

**Comment by teraa** [comment]
There is no single mention of "reason" on that page, what are you referring to?
