### ISSUE TITLE
Shouldn't throw exceptions, but give the developer a warning / log.

### ISSUE THREAD

**Issue by BjornGameDev** [TwitchLib/TwitchLib.Client#14]
If you add a OnBeingHosted event on a new channel that isn't the as the TwitchUsername, it shouldn't an throw Exception and break the app, but rather log a warning.

Same applies on getting moderators, but not listening on OnModeratorsReceived.

This might cause the app to break and stop working without getting any notice if TwitchLib runs on a separate thread. Also these are just good to know, not fatal issues.

**Comment by swiftyspiffy** [comment]
Wow, not sure how I didn't see this issue get created. I agree with you. Will work to get this fixed. Sorry about the delay.

**Comment by swiftyspiffy** [comment]
This has been resolved :D
