### ISSUE TITLE
reconnect() System.StackOverflowException

### ISSUE THREAD

**Issue by BenK1337** [TwitchLib/TwitchLib.Client#142]
Hi im running into an StackOverflowException.

All is working fine, but if the bot gets disconnect, the event is fired like 1k times.
I realy can't figure out why. Any suggestions?

 `protected TwitchClient client;`

 `public Bot() `
 `{ `
`    ConnectionCredentials credentials = new ConnectionCredentials("xxxx", "xxxx");`
`     client = new TwitchClient();`
`     client.Initialize(credentials, "xxxx");`
`     client.OnLog += Client_OnLog;`
`     client.OnConnected += Client_OnConnected;`
`     client.OnDisconnected += Client_OnDisconnected;`
`     client.Connect();`
`}`    

`        private void Client_OnDisconnected(object sender, OnDisconnectedEventArgs e)`
`        {`
`            client.Reconnect();`
`        }`

`static void Main()`
`{`
   `  Bot = new Bot();`
    ` BotService.RunBotAsync().ConfigureAwait(false).GetAwaiter().GetResult();       `
`}`

**Console:**

`28.03.2020 15:11:10: communitygamesbot - Reconnecting to Twitch`
`28.03.2020 15:11:10: communitygamesbot - Reconnecting to Twitch`
`. . .`
`. . .`
`28.03.2020 15:11:10: communitygamesbot - Reconnecting to Twitch`
`Process is terminated due to StackOverflowException``

**Comment by zAfLu** [comment]
Can confirm.

**Comment by nvmp-main** [comment]
Additional confirmation, hitting this today

**Comment by swiftyspiffy** [comment]
I think we (Syzuna and I) just stumbled on the problem here:

https://github.com/TwitchLib/TwitchLib.Communication/blob/master/src/TwitchLib.Communication/Clients/TcpClient.cs#L95

If you disconnect, there's no sleep here, so you'll blow the stack on this recursive call. This exists in Websocket client as well. The short term fix I think is to add a sleep before the recursive call. Recursion here is probably not the best idea though.

**Comment by B1ack3ye** [comment]
Is there currently a good workaround for this?

I have the same problem with the WebSocketClient.

A simple sleep command is not enough, but unfortunately my experience is not enough to block an event from firing again until the client has tried to reconnect.

**Comment by B1ack3ye** [comment]
I tried to solve the problem and discovered the following:

       

        private bool NetworkAviable = false;
        
        private void TwitchClient_OnReconnected(object? sender, TwitchLib.Communication.Events.OnReconnectedEventArgs e)
        {
            Console.WriteLine(e.ToString());
        }

        private void TwitchClient_OnDisconnected(object? sender, TwitchLib.Communication.Events.OnDisconnectedEventArgs e)
        {
            twitchClient.OnDisconnected -= TwitchClient_OnDisconnected;
            NetworkChange.NetworkAvailabilityChanged += NetworkChange_NetworkAvailabilityChanged;
            while (NetworkAviable == false)
            {
                Thread.Sleep(1000);
            }
            twitchClient.Reconnect();
            Console.WriteLine("Debug Line");
            twitchClient.OnDisconnected += TwitchClient_OnDisconnected;
        }

        private void NetworkChange_NetworkAvailabilityChanged(object? sender, NetworkAvailabilityEventArgs e)
        {
            NetworkAviable = e.IsAvailable;
        }


I have caused a disconnect in the Windows settings by disabling the network connection.
After 1 second, I re-enabled the connection and the console displayed this:

TwitchLib.Communication.Events.OnReconnectedEventArgs
Debug Line
TwitchLib.Communication.Events.OnReconnectedEventArgs

The bot did not reestablish the connection.
To me it looks like the reconnect method is not working. 

I use the version of TwitchLib 3.2.0 (Nuget) and the TwitchLib client version 3.2.3.

**Comment by swiftyspiffy** [comment]
Closing this as it has likely been resolved with changes to the Communication library.
