### ISSUE TITLE
Can it catch rewards?

### ISSUE THREAD

**Issue by MaestroMagnifico** [TwitchLib/TwitchLib.Client#145]
Hey. I'm trying to create chat bot that can launch some actions when people redeem rewards. I was able to catch rewards with user text because I can see it in `OnMessageReceived` and it comes with `e.ChatMessage.CustomRewardId`. But is there a way to catch rewards without user text?

Also, quick request. Can you also add `e.ChatMessage.CustomRewardName`? Thanks.

**Comment by Bappsack** [comment]
u need a pubsub event for rewards if u mean channel points.

```
pubSub.OnRewardRedeemed += onRewardRedeemed;
pubSub.ListenToRewards(ChannelID);

```

**Comment by MaestroMagnifico** [comment]
Well, I initialized it like this and it doesn't work. I got channel id here by creating new app: https://dev.twitch.tv/console/apps

```
TwitchPubSub pubSub = new TwitchPubSub();

private void Form1_Load(object sender, EventArgs e)
{
    pubSub.ListenToRewards("my_channel_id"); 
    pubSub.OnRewardRedeemed += new EventHandler<OnRewardRedeemedArgs>(onRewardRedeemed);
}

private void onRewardRedeemed(object sender, OnRewardRedeemedArgs e)
{
    MessageBox.Show(e.RewardTitle); // this line doesn't shoot
}
```

**Comment by Bappsack** [comment]
@Mahsaap close please since the author don't.

**Comment by Mahsaap** [comment]
i cant close
