### ISSUE TITLE
Cant join multiple channels in quick succession reliably

### ISSUE THREAD

**Issue by negativeeddy** [TwitchLib/TwitchLib.Client#147]
If a JoinChannel is attempted immediately after Connect one of the channels may not get joined (or the default channel might not get joined).

To demonstrate this just add a call to JoinChannel() immediately after Connect() in the C# sample. And try it a half dozen times

I also tried waiting for the IsConnected() property to go true and then call JoinChannel() but I still get the same inconsistent behavior.

In the logs, both the "Joining Channel XXX" messages appear but when one fails there is an entry regarding rejecting an identical 

```
Your message was not sent because it is identical to the previous one you sent, less than 30 seconds ago.
```

**Comment by Syzuna** [comment]
but if you got some spare minutes and can come up with a quick fix feel free to do a PR for it

**Comment by negativeeddy** [comment]
yeah i'll try to do a little digging next week
