### ISSUE TITLE
Problem with emote parsing

### ISSUE THREAD

**Issue by Urantij** [TwitchLib/TwitchLib.Client#154]
Recently i had exception in GetEmote method of EmoteExtractor class, ArgumentOutOfRangeException.
emoteData is `84608:51-58`
message is `ипать... пашкет на фоне алтала - оперный певец... cmonBruh`

```
if (single)
{
    startIndex = int.Parse(emoteData.Split(':')[1].Split('-')[0]);
    endIndex = int.Parse(emoteData.Split(':')[1].Split('-')[1]);
}
else
{
    startIndex = int.Parse(emoteData.Split('-')[0]);
    endIndex = int.Parse(emoteData.Split('-')[1]);
}

string name = message.Substring(startIndex, (endIndex - startIndex) + 1);
```

`message.Substring(startIndex, (endIndex - startIndex) + 1)`
Will throw exception, working option would be
`message.Substring(startIndex - 1, (endIndex - startIndex) + 1)`
Maybe twitch is assuming, that string is starting with 1 instead of 0, i havent checked this topic too much.

**Comment by swiftyspiffy** [comment]
This should resolved via a couple commits, but most prominently https://github.com/TwitchLib/TwitchLib.Client/commit/29157f15cf0c29cb6eb08feee347ebdd2ecc873b . Closing this. Feel free to comment to have it reopened if it's still an issue.
