### ISSUE TITLE
Support deleting individual messages

### ISSUE THREAD

**Issue by Felk** [TwitchLib/TwitchLib.Client#158]
TwitchLib does not seem to support the deletion of individual messages. TMI supports it as an improvement over the good old 1-second timeout, which unfortunately deletes all of a user's messages instead of just one.

According to [this post from 2018](https://discuss.dev.twitch.tv/t/deleting-single-messages/15916/3?u=felk) deleting only one specific message is done by passing the IRC tag `target-msg-id` to the PRIVMSG containing the timeout command.

**Comment by Mahsaap** [comment]
Just send i think /delete msg-id in chat

**Comment by Felk** [comment]
wow, that is easy. thank you!

**Comment by Syzuna** [comment]
An extension method for deleting a message is already available in the PreRelease Dev Build.
It just did not make it into the "Stable" version yet although I would call the current PreRelease Builds as stable as the full release.

**Comment by Felk** [comment]
That's great news, thank you
