### ISSUE TITLE
autojoin channel not rejoined after reconnect since version 3.2.0.0

### ISSUE THREAD

**Issue by Felk** [TwitchLib/TwitchLib.Client#163]
I'm essentially just converting my comment on https://github.com/TwitchLib/TwitchLib.Client/pull/140 into an issue. Since version 3.2.0.0 the TwitchLib Client appears to no longer automatically join the channels configured in the `Initialize(...)` call after connecting once. The linked merge request seems to have caused this regression. Looks like the `_autoJoinChannel` field is now unused, and instead `Initialize(...)` fills the `_joinChannelQueue`, which gets cleared after the respective channel was joined once.

Workaround is to manually hook into `IsConnected` event and join channels there, e.g.
```C#
_twitchClient.OnConnected += (_, _) => _twitchClient.JoinChannel("mychannel");
```

**Comment by swiftyspiffy** [comment]
Looking into this.

**Comment by Syzuna** [comment]
We rewrote a good portion of the code handling IRC and Channel joining.
If this is still an issue please make a new issue with new info
