### ISSUE TITLE
Client_OnConnected OnConnectedArgs e.AutoJoinChannel NULL

### ISSUE THREAD

**Issue by ghost** [TwitchLib/TwitchLib.Client#171]
Console.WriteLine($"Connected to {e.AutoJoinChannel}");

e.AutoJoinChannel is null

**Comment by Mahsaap** [comment]
https://github.com/TwitchLib/TwitchLib.Client/commit/2803284ba4fa01cc5bb6ca2109a2af30d6b6a2c3

That looks to should have been removed on that commit but was missed @swiftyspiffy

**Comment by swiftyspiffy** [comment]
Out of date
