### ISSUE TITLE
OnModeratorJoined apparently not firing

### ISSUE THREAD

**Issue by WrithemTwine** [TwitchLib/TwitchLib.Client#172]
Doesn't seem to fire when moderators join the channel. Should've set a breakpoint, but code I have saves/counts unique mods joined (through event) and when a stream ends, no mods appear as arrived but I've seen them chat and in channel user list.

Workaround is checking if they chat a message.

Nuget TwitchLib.Client (3.2.2)

**Comment by Syzuna** [comment]
The IRC command powering this functionality has been removed by Twitch.
It was an oversight that we didnt remove it from the lib yet. 
You would either need keep checking the messages for mod status or get a list of moderators of a channel from the GetModerators API endpoint (needs broadcaster auth with a scope tho)
