### ISSUE TITLE
ChatReply Message Content

### ISSUE THREAD

**Issue by Bappsack** [TwitchLib/TwitchLib.Client#175]
the ChatReply class doesn't contain a Message Content Property and ChatMessage.Message does not have the Reply Message in.

**Comment by swiftyspiffy** [comment]
2 years late, but taking a look.

**Comment by swiftyspiffy** [comment]
![image](https://github.com/TwitchLib/TwitchLib.Client/assets/9569194/784606dc-ab40-4609-91e8-bb0f2b06e0fe)
![image](https://github.com/TwitchLib/TwitchLib.Client/assets/9569194/946229a5-ca4a-48b8-a8aa-dfd9dcee2e57)

**Comment by swiftyspiffy** [comment]
This looks like correct behavior. I'm going to close this, feel free to reopen if you're expecting something else.
