### ISSUE TITLE
Twitch Client, No Permissions

### ISSUE THREAD

**Issue by A5ho9999** [TwitchLib/TwitchLib.Client#179]
So I worked on a little auto-mod system for a Streamer but when it gets triggered it results in a No Permission error even though the Account being used is a Mod on the channel? What is the requirements for this to work? The Action trying to be performed is just Timeout or Banning.

**Comment by Syzuna** [comment]
The token you use to log into chat needs the "channel:moderate" scope to be allowed to perform mod actions via IRC

**Comment by A5ho9999** [comment]
Does that scope require permission from the streamer? Or can be applied without it?

**Comment by A5ho9999** [comment]
Okay, great. Thank you.
