### ISSUE TITLE
Unaccounted for: Login authentication failed

### ISSUE THREAD

**Issue by Vivelin** [TwitchLib/TwitchLib.Client#187]
If I try to initialize and connect with an invalid token (e.g. adding a bunch of garbage at the end of the token for testing purposes), the following message is logged:

`TwitchLib.Client.TwitchClient: Information: [TwitchLib, 3.2.6.0] Unaccounted for: :tmi.twitch.tv NOTICE * :Login authentication failed (please create a TwitchLib GitHub issue :P)`

Assembly version: 3.2.6.0

**Comment by Syzuna** [comment]
This was fixed in #192
