### ISSUE TITLE
GetChannelModerators() is not working

### ISSUE THREAD

**Issue by mast3rm1nd** [TwitchLib/TwitchLib.Client#19]
GetChannelModerators() is not working

**Comment by Mahsaap** [comment]
what version are you on? That text from twitch has changed and updated in latest. "should be"

**Comment by mast3rm1nd** [comment]
latest from NuGet - 2.0.1

**Comment by Mahsaap** [comment]
Had it previously worked? Or this a new build. Someone else said it works for him. So only thing I can think of is if it's a new bot, does your token have the required scope?

Otherwise someone else will have to take a stab.

**Comment by mast3rm1nd** [comment]
it worked and suddenly it's not ><

**Comment by Mahsaap** [comment]
Ok I'll relay the information. Twitch may have changed something.

**Comment by Syzuna** [comment]
so yeah just looked into my production bots logs and it looks to run as expected for me.

To help you debug or to find an issue that doesnt effect anyone we need more information tho.

Sth like is there any error/exception that is thrown or a pastebin/github gist of the effected code

**Comment by swiftyspiffy** [comment]
Hey!

There was a fix put in for GetChannelModerators somewhat recently. Not sure if it made its way into the latest package. I should exist in the current master branch though.

**Comment by swiftyspiffy** [comment]
Will go ahead and close this. Feel free to reopen as necessary.
