### ISSUE TITLE
Cannot send message no_permission

### ISSUE THREAD

**Issue by MTrinkiesJr** [TwitchLib/TwitchLib.Client#191]
Hey there,

I just created a BoT Server with you Lib. But I'm not able to send messages to a channel.
For my steps, so what I'm doing.

1. Created a Twitch BOT Account
2. Getting the Access Token for that BOT Account with the ClientID from the Devleoper Console via Authorization Code Flow
Following Scopes are requested:
- "bits:read",
- "channel:manage:polls",
- "channel:manage:predictions",
- "channel:manage:redemptions",
- "channel:read:goals",
- "channel:read:hype_train",
- "channel:read:predictions",
- "channel:read:redemptions",
- "channel:read:subscriptions",
- "moderation:read",
- "moderator:manage:banned_users",
- "moderator:read:blocked_terms",
- "moderator:manage:blocked_terms",
- "moderator:manage:automod",
- "moderator:read:automod_settings",
- "moderator:read:chat_settings",
- "moderator:manage:chat_settings",
- "user:edit",
- "user:manage:blocked_users",
- "user:read:email",
- "user:read:follows",
- "user:read:subscriptions",
- "channel:moderate",
- "chat:read",
- "whispers:read",
- "whispers:edit",
- "chat:edit"    

4. Init Client with credentials
5. Join the Channel
6. Trying to send message "pong!" on "!ping" command

Here is my code:

`        public async Task ConnectAsync()
        {
            var accessToken = await _tokenHandler.EnsureAccessTokenAsync();

            if (string.IsNullOrEmpty(accessToken))
            {
                _logger.LogCritical("No access token received, cannot initialize channel service for '{CannelName}'", Channel.Name);
            }

            var credentials = new ConnectionCredentials(Channel.BotName, accessToken, capabilities: new Capabilities());
            var clientOptions = new ClientOptions()
            {
                ClientType = ClientType.Chat,
                ThrottlingPeriod = TimeSpan.FromSeconds(30),
                MessagesAllowedInPeriod = 750,
                SendQueueCapacity = 750,
                ReconnectionPolicy = new ReconnectionPolicy(1000, 10)
            };

            _socketClient = new WebSocketClient(clientOptions);
            _socketClient.OnError += SocketClientOnOnError;
            _socketClient.OnData += SocketClientOnOnData;
            _socketClient.OnFatality += SocketClientOnOnFatality;
            _socketClient.OnMessage += SocketClientOnOnMessage;
            _socketClient.OnSendFailed += SocketClientOnOnSendFailed;
            var logger = _loggerFactory.CreateLogger<TwitchClient>();
            _client = new TwitchClient(_socketClient, logger: logger);
            _client.AutoReListenOnException = true;
            _client.Initialize(credentials, Channel.Name.ToLower(), Channel.CommandIdentifier);
            _client.OnChannelStateChanged += ClientOnOnChannelStateChanged;
            _client.OnConnected += ClientOnOnConnected;
            _client.OnConnectionError += ClientOnOnConnectionError;
            _client.OnJoinedChannel += ClientOnOnJoinedChannel;
            _client.OnLeftChannel += ClientOnOnLeftChannel;
            _client.OnError += ClientOnOnError;
            _client.OnMessageReceived += ClientOnOnMessageReceived;
            _client.OnFailureToReceiveJoinConfirmation += ClientOnOnFailureToReceiveJoinConfirmation;
            _client.OnIncorrectLogin += ClientOnOnIncorrectLogin;
            _client.OnMessageThrottled += ClientOnOnMessageThrottled;
            _client.OnSendReceiveData += ClientOnOnSendReceiveData;
            _client.OnNoPermissionError += ClientOnOnNoPermissionError;

            _client.Connect();
        }

        private void ClientOnOnNoPermissionError(object? sender, EventArgs e)
        {
            _logger.LogWarning("No permission to do that");
        }

        private void ClientOnOnSendReceiveData(object? sender, OnSendReceiveDataArgs e)
        {
            _logger.LogInformation($"Client SendReceive: '{e.Direction}': '{e.Data}'");
        }

        private void ClientOnOnMessageThrottled(object? sender, OnMessageThrottledEventArgs e)
        {
            _logger.LogInformation($"Client message throttled: '{e.Message}'; allowed: '{e.AllowedInPeriod}'; send messages: '{e.SentMessageCount}'");
        }

        private void ClientOnOnIncorrectLogin(object? sender, OnIncorrectLoginArgs e)
        {
            _logger.LogError(e.Exception, "Client incorrect login");
        }

        private void ClientOnOnFailureToReceiveJoinConfirmation(object? sender, OnFailureToReceiveJoinConfirmationArgs e)
        {
            _logger.LogCritical($"Failed to receive join confirmation: {e.Exception.Channel}: '{e.Exception.Details}'");
        }

        private void ClientOnOnChannelStateChanged(object? sender, OnChannelStateChangedArgs e)
        {
            _logger.LogDebug($"Channel state changed for '{e.Channel}' to '{JsonConvert.SerializeObject(e.ChannelState)}'");
        }

        private void ClientOnOnMessageReceived(object? sender, OnMessageReceivedArgs e)
        {
            if (e.ChatMessage.Message == "!ping")
            {
                _logger.LogInformation("'!ping' received");
                _logger.LogInformation("Trying so send message 'pong!'");
                _client.SendMessage(Channel.Name.ToLower(), "pong!");
            }
        }

        private void SocketClientOnOnSendFailed(object? sender, OnSendFailedEventArgs e)
        {
            _logger.LogError(e.Exception, $"Send failed");
        }

        private void SocketClientOnOnMessage(object? sender, OnMessageEventArgs e)
        {
            _logger.LogDebug($"Socket message: '{e.Message}'");
        }

        private void SocketClientOnOnFatality(object? sender, OnFatalErrorEventArgs e)
        {
            _logger.LogError(e.Reason, $"Socket fatal");
        }

        private void SocketClientOnOnError(object? sender, OnErrorEventArgs e)
        {
            _logger.LogError(e.Exception, $"Socket client error");
        }

        private void SocketClientOnOnData(object? sender, OnDataEventArgs e)
        {

        }

        private void ClientOnOnError(object? sender, OnErrorEventArgs e)
        {
            _logger.LogError(e.Exception, $"Client error");
        }

        private void ClientOnOnLeftChannel(object? sender, OnLeftChannelArgs e)
        {
            _logger.LogDebug($"Client left channel: '{e.Channel}'");
        }

        private void ClientOnOnJoinedChannel(object? sender, OnJoinedChannelArgs e)
        {
            _logger.LogInformation($"Client joined {e.Channel}");
        }

        private void ClientOnOnConnectionError(object? sender, OnConnectionErrorArgs e)
        {
            _logger.LogError(e.Error.Message, $"Client connection error");
        }

        private void ClientOnOnConnected(object? sender, OnConnectedArgs e)
        {
            _logger.LogInformation($"Client connected to: '{e.AutoJoinChannel}'");
            
            _client.JoinChannel(Channel.Name.ToLower());
        }`

And here my logs

- 2022-05-28 19:55:54.5370 | Info  | TwitchLib.Client.TwitchClient |  | [TwitchLib, 3.2.4.0] TwitchLib-TwitchClient initialized, assembly version: 3.2.4.0 |
- 2022-05-28 19:55:54.5370 | Info  | TwitchLib.Client.TwitchClient |  | [TwitchLib, 3.2.4.0] Connecting to: wss://irc-ws.chat.twitch.tv:443 |
- 2022-05-28 19:55:59.9863 | Info  | TwitchLib.Client.TwitchClient |  | [TwitchLib, 3.2.4.0] Should be connected! |
- 2022-05-28 19:56:00.0389 | Info  | TwitchLib.Client.TwitchClient |  | [TwitchLib, 3.2.4.0] Joining channel: {REDACTED_CHANNEL_NAME} |
- 2022-05-28 19:56:01.7343 | Debug | BotChannelService_{REDACTED_CHANNEL_NAME} |  | Socket message: ':tmi.twitch.tv 001 {REDACTED_BOT_NAME} :Welcome, GLHF!
- :tmi.twitch.tv 002 {REDACTED_BOT_NAME} :Your host is tmi.twitch.tv
- :tmi.twitch.tv 003 {REDACTED_BOT_NAME} :This server is rather new
- :tmi.twitch.tv 004 {REDACTED_BOT_NAME} :-
- :tmi.twitch.tv 375 {REDACTED_BOT_NAME} :-
- :tmi.twitch.tv 372 {REDACTED_BOT_NAME} :You are in a maze of twisty passages, all alike.
- :tmi.twitch.tv 376 {REDACTED_BOT_NAME} :>
- ' |
- 2022-05-28 19:56:01.7343 | Info  | TwitchLib.Client.TwitchClient |  | [TwitchLib, 3.2.4.0] Received: :tmi.twitch.tv 001 {REDACTED_BOT_NAME} :Welcome, GLHF! |
- 2022-05-28 19:56:01.7343 | Info  | BotChannelService_{REDACTED_CHANNEL_NAME} |  | Client SendReceive: 'Received': ':tmi.twitch.tv 001 {REDACTED_BOT_NAME} :Welcome, GLHF!' |
- 2022-05-28 19:56:01.7343 | Info  | TwitchLib.Client.TwitchClient |  | [TwitchLib, 3.2.4.0] Received: :tmi.twitch.tv 002 {REDACTED_BOT_NAME} :Your host is tmi.twitch.tv |
- 2022-05-28 19:56:01.7343 | Info  | BotChannelService_{REDACTED_CHANNEL_NAME} |  | Client SendReceive: 'Received': ':tmi.twitch.tv 002 {REDACTED_BOT_NAME} :Your host is tmi.twitch.tv' |
- 2022-05-28 19:56:01.7343 | Info  | TwitchLib.Client.TwitchClient |  | [TwitchLib, 3.2.4.0] Received: :tmi.twitch.tv 003 {REDACTED_BOT_NAME} :This server is rather new |
- 2022-05-28 19:56:01.7343 | Info  | BotChannelService_{REDACTED_CHANNEL_NAME} |  | Client SendReceive: 'Received': ':tmi.twitch.tv 003 {REDACTED_BOT_NAME} :This server is rather new' |
- 2022-05-28 19:56:01.7343 | Info  | TwitchLib.Client.TwitchClient |  | [TwitchLib, 3.2.4.0] Received: :tmi.twitch.tv 004 {REDACTED_BOT_NAME} :- |
- 2022-05-28 19:56:01.7343 | Info  | BotChannelService_{REDACTED_CHANNEL_NAME} |  | Client SendReceive: 'Received': ':tmi.twitch.tv 004 {REDACTED_BOT_NAME} :-' |
- 2022-05-28 19:56:01.7343 | Info  | BotChannelService_{REDACTED_CHANNEL_NAME} |  | Client connected to: '' |
- 2022-05-28 19:56:04.5691 | Info  | TwitchLib.Client.TwitchClient |  | [TwitchLib, 3.2.4.0] Received: :tmi.twitch.tv 375 {REDACTED_BOT_NAME} :- |
- 2022-05-28 19:56:04.5691 | Info  | BotChannelService_{REDACTED_CHANNEL_NAME} |  | Client SendReceive: 'Received': ':tmi.twitch.tv 375 {REDACTED_BOT_NAME} :-' |
- 2022-05-28 19:56:04.5691 | Info  | TwitchLib.Client.TwitchClient |  | [TwitchLib, 3.2.4.0] Received: :tmi.twitch.tv 372 {REDACTED_BOT_NAME} :You are in a maze of twisty passages, all alike. |
- 2022-05-28 19:56:04.5691 | Info  | BotChannelService_{REDACTED_CHANNEL_NAME} |  | Client SendReceive: 'Received': ':tmi.twitch.tv 372 {REDACTED_BOT_NAME} :You are in a maze of twisty passages, all alike.' |
- 2022-05-28 19:56:04.5691 | Info  | TwitchLib.Client.TwitchClient |  | [TwitchLib, 3.2.4.0] Received: :tmi.twitch.tv 376 {REDACTED_BOT_NAME} :> |
- 2022-05-28 19:56:04.5691 | Info  | BotChannelService_{REDACTED_CHANNEL_NAME} |  | Client SendReceive: 'Received': ':tmi.twitch.tv 376 {REDACTED_BOT_NAME} :>' |
- 2022-05-28 19:56:04.5691 | Debug | BotChannelService_{REDACTED_CHANNEL_NAME} |  | Socket message: ':tmi.twitch.tv CAP * ACK :twitch.tv/membership
- ' |
- 2022-05-28 19:56:04.5691 | Info  | TwitchLib.Client.TwitchClient |  | [TwitchLib, 3.2.4.0] Received: :tmi.twitch.tv CAP * ACK :twitch.tv/membership |
- 2022-05-28 19:56:04.5691 | Info  | BotChannelService_{REDACTED_CHANNEL_NAME} |  | Client SendReceive: 'Received': ':tmi.twitch.tv CAP * ACK :twitch.tv/membership' |
- 2022-05-28 19:56:04.5691 | Info  | TwitchLib.Client.TwitchClient |  | [TwitchLib, 3.2.4.0] Unaccounted for: :tmi.twitch.tv CAP * ACK :twitch.tv/membership (please create a TwitchLib GitHub issue :P) |
- 2022-05-28 19:56:04.5691 | Debug | BotChannelService_{REDACTED_CHANNEL_NAME} |  | Socket message: ':tmi.twitch.tv CAP * ACK :twitch.tv/commands
- ' |
- 2022-05-28 19:56:04.5691 | Info  | TwitchLib.Client.TwitchClient |  | [TwitchLib, 3.2.4.0] Received: :tmi.twitch.tv CAP * ACK :twitch.tv/commands |
- 2022-05-28 19:56:04.5691 | Info  | BotChannelService_{REDACTED_CHANNEL_NAME} |  | Client SendReceive: 'Received': ':tmi.twitch.tv CAP * ACK :twitch.tv/commands' |
- 2022-05-28 19:56:04.5691 | Info  | TwitchLib.Client.TwitchClient |  | [TwitchLib, 3.2.4.0] Unaccounted for: :tmi.twitch.tv CAP * ACK :twitch.tv/commands (please create a TwitchLib GitHub issue :P) |
- 2022-05-28 19:56:04.7502 | Debug | BotChannelService_{REDACTED_CHANNEL_NAME} |  | Socket message: ':tmi.twitch.tv CAP * ACK :twitch.tv/tags
- ' |
- 2022-05-28 19:56:04.7502 | Info  | TwitchLib.Client.TwitchClient |  | [TwitchLib, 3.2.4.0] Received: :tmi.twitch.tv CAP * ACK :twitch.tv/tags |
- 2022-05-28 19:56:04.7502 | Info  | BotChannelService_{REDACTED_CHANNEL_NAME} |  | Client SendReceive: 'Received': ':tmi.twitch.tv CAP * ACK :twitch.tv/tags' |
- 2022-05-28 19:56:04.7502 | Info  | TwitchLib.Client.TwitchClient |  | [TwitchLib, 3.2.4.0] Unaccounted for: :tmi.twitch.tv CAP * ACK :twitch.tv/tags (please create a TwitchLib GitHub issue :P) |
- 2022-05-28 19:56:05.2882 | Debug | BotChannelService_{REDACTED_CHANNEL_NAME} |  | Socket message: ':{REDACTED_BOT_NAME}!{REDACTED_BOT_NAME}@{REDACTED_BOT_NAME}.tmi.twitch.tv JOIN #{REDACTED_CHANNEL_NAME}
- :{REDACTED_BOT_NAME}.tmi.twitch.tv 353 {REDACTED_BOT_NAME} = #{REDACTED_CHANNEL_NAME} :{REDACTED_BOT_NAME}
- :{REDACTED_BOT_NAME}.tmi.twitch.tv 366 {REDACTED_BOT_NAME} #{REDACTED_CHANNEL_NAME} :End of /NAMES list
- @badge-info=;badges=moderator/1;color=;display-name={REDACTED_BOT_NAME};emote-sets=0;mod=1;subscriber=0;user-type=mod :tmi.twitch.tv USERSTATE #{REDACTED_CHANNEL_NAME}
- @emote-only=0;followers-only=-1;r9k=0;rituals=0;room-id={REDACTED_ROOM_ID};slow=0;subs-only=0 :tmi.twitch.tv ROOMSTATE #{REDACTED_CHANNEL_NAME}
- ' |
- 2022-05-28 19:56:05.2882 | Info  | TwitchLib.Client.TwitchClient |  | [TwitchLib, 3.2.4.0] Received: :{REDACTED_BOT_NAME}!{REDACTED_BOT_NAME}@{REDACTED_BOT_NAME}.tmi.twitch.tv JOIN #{REDACTED_CHANNEL_NAME} |
- 2022-05-28 19:56:05.2882 | Info  | BotChannelService_{REDACTED_CHANNEL_NAME} |  | Client SendReceive: 'Received': ':{REDACTED_BOT_NAME}!{REDACTED_BOT_NAME}@{REDACTED_BOT_NAME}.tmi.twitch.tv JOIN #{REDACTED_CHANNEL_NAME}' |
- 2022-05-28 19:56:05.2882 | Info  | TwitchLib.Client.TwitchClient |  | [TwitchLib, 3.2.4.0] Received: :{REDACTED_BOT_NAME}.tmi.twitch.tv 353 {REDACTED_BOT_NAME} = #{REDACTED_CHANNEL_NAME} :{REDACTED_BOT_NAME} |
- 2022-05-28 19:56:05.2882 | Info  | BotChannelService_{REDACTED_CHANNEL_NAME} |  | Client SendReceive: 'Received': ':{REDACTED_BOT_NAME}.tmi.twitch.tv 353 {REDACTED_BOT_NAME} = #{REDACTED_CHANNEL_NAME} :{REDACTED_BOT_NAME}' |
- 2022-05-28 19:56:05.2882 | Info  | TwitchLib.Client.TwitchClient |  | [TwitchLib, 3.2.4.0] Received: :{REDACTED_BOT_NAME}.tmi.twitch.tv 366 {REDACTED_BOT_NAME} #{REDACTED_CHANNEL_NAME} :End of /NAMES list |
- 2022-05-28 19:56:05.2882 | Info  | BotChannelService_{REDACTED_CHANNEL_NAME} |  | Client SendReceive: 'Received': ':{REDACTED_BOT_NAME}.tmi.twitch.tv 366 {REDACTED_BOT_NAME} #{REDACTED_CHANNEL_NAME} :End of /NAMES list' |
- 2022-05-28 19:56:05.2882 | Info  | TwitchLib.Client.TwitchClient |  | [TwitchLib, 3.2.4.0] Finished channel joining queue. |
- 2022-05-28 19:56:05.2882 | Info  | TwitchLib.Client.TwitchClient |  | [TwitchLib, 3.2.4.0] Received: @badge-info=;badges=moderator/1;color=;display-name={REDACTED_BOT_NAME};emote-sets=0;mod=1;subscriber=0;user-type=mod :tmi.twitch.tv USERSTATE #{REDACTED_CHANNEL_NAME} |
- 2022-05-28 19:56:05.2882 | Info  | BotChannelService_{REDACTED_CHANNEL_NAME} |  | Client SendReceive: 'Received': '@badge-info=;badges=moderator/1;color=;display-name={REDACTED_BOT_NAME};emote-sets=0;mod=1;subscriber=0;user-type=mod :tmi.twitch.tv USERSTATE #{REDACTED_CHANNEL_NAME}' |
- 2022-05-28 19:56:05.2882 | Info  | TwitchLib.Client.TwitchClient |  | [TwitchLib, 3.2.4.0] Received: @emote-only=0;followers-only=-1;r9k=0;rituals=0;room-id={REDACTED_ROOM_ID};slow=0;subs-only=0 :tmi.twitch.tv ROOMSTATE #{REDACTED_CHANNEL_NAME} |
- 2022-05-28 19:56:05.2882 | Info  | BotChannelService_{REDACTED_CHANNEL_NAME} |  | Client SendReceive: 'Received': '@emote-only=0;followers-only=-1;r9k=0;rituals=0;room-id={REDACTED_ROOM_ID};slow=0;subs-only=0 :tmi.twitch.tv ROOMSTATE #{REDACTED_CHANNEL_NAME}' |
- 2022-05-28 19:56:05.2931 | Info  | BotChannelService_{REDACTED_CHANNEL_NAME} |  | Client joined {REDACTED_CHANNEL_NAME} |
- 2022-05-28 19:56:05.2931 | Debug | BotChannelService_{REDACTED_CHANNEL_NAME} |  | Channel state changed for '{REDACTED_CHANNEL_NAME}' to '{"BroadcasterLanguage":null,"Channel":"{REDACTED_CHANNEL_NAME}","EmoteOnly":false,"FollowersOnly":null,"Mercury":false,"R9K":false,"Rituals":false,"RoomId":"{REDACTED_ROOM_ID}","SlowMode":0,"SubOnly":false}' |
- 2022-05-28 19:56:05.5773 | Info  | TwitchLib.Client.TwitchClient |  | [TwitchLib, 3.2.4.0] Finished channel joining queue. |
- 2022-05-28 19:56:07.7065 | Debug | BotChannelService_{REDACTED_CHANNEL_NAME} |  | Socket message: ':moobot!moobot@moobot.tmi.twitch.tv JOIN #{REDACTED_CHANNEL_NAME}
- :{REDACTED_CHANNEL_NAME}!{REDACTED_CHANNEL_NAME}@{REDACTED_CHANNEL_NAME}.tmi.twitch.tv JOIN #{REDACTED_CHANNEL_NAME}
- ' |
- 2022-05-28 19:56:07.7065 | Info  | TwitchLib.Client.TwitchClient |  | [TwitchLib, 3.2.4.0] Received: :moobot!moobot@moobot.tmi.twitch.tv JOIN #{REDACTED_CHANNEL_NAME} |
- 2022-05-28 19:56:07.7065 | Info  | BotChannelService_{REDACTED_CHANNEL_NAME} |  | Client SendReceive: 'Received': ':moobot!moobot@moobot.tmi.twitch.tv JOIN #{REDACTED_CHANNEL_NAME}' |
- 2022-05-28 19:56:07.7065 | Info  | TwitchLib.Client.TwitchClient |  | [TwitchLib, 3.2.4.0] Received: :{REDACTED_CHANNEL_NAME}!{REDACTED_CHANNEL_NAME}@{REDACTED_CHANNEL_NAME}.tmi.twitch.tv JOIN #{REDACTED_CHANNEL_NAME} |
- 2022-05-28 19:56:07.7065 | Info  | BotChannelService_{REDACTED_CHANNEL_NAME} |  | Client SendReceive: 'Received': ':{REDACTED_CHANNEL_NAME}!{REDACTED_CHANNEL_NAME}@{REDACTED_CHANNEL_NAME}.tmi.twitch.tv JOIN #{REDACTED_CHANNEL_NAME}' |
- 2022-05-28 19:56:08.5113 | Debug | BotChannelService_{REDACTED_CHANNEL_NAME} |  | Socket message: '@badge-info=;badges=broadcaster/1,premium/1;client-nonce={REDACTED_NONCE};color=#008000;display-name={REDACTED_CHANNEL_NAME};emotes=;first-msg=0;flags=;id={REDACTED_ID};mod=0;room-id={REDACTED_ROOM_ID};subscriber=0;tmi-sent-ts=1653760568213;turbo=0;user-id={REDACTED_ROOM_ID};user-type= :{REDACTED_CHANNEL_NAME}!{REDACTED_CHANNEL_NAME}@{REDACTED_CHANNEL_NAME}.tmi.twitch.tv PRIVMSG #{REDACTED_CHANNEL_NAME} :!ping
- ' |
- 2022-05-28 19:56:08.5113 | Info  | TwitchLib.Client.TwitchClient |  | [TwitchLib, 3.2.4.0] Received: @badge-info=;badges=broadcaster/1,premium/1;client-nonce={REDACTED_NONCE};color=#008000;display-name={REDACTED_CHANNEL_NAME};emotes=;first-msg=0;flags=;id=cc1c04b6-08de-45c1-9c79-6f2f62faecbb;mod=0;room-id={REDACTED_ROOM_ID};subscriber=0;tmi-sent-ts=1653760568213;turbo=0;user-id={REDACTED_ROOM_ID};user-type= :{REDACTED_CHANNEL_NAME}!{REDACTED_CHANNEL_NAME}@{REDACTED_CHANNEL_NAME}.tmi.twitch.tv PRIVMSG #{REDACTED_CHANNEL_NAME} :!ping |
- 2022-05-28 19:56:08.5113 | Info  | BotChannelService_{REDACTED_CHANNEL_NAME} |  | Client SendReceive: 'Received': '@badge-info=;badges=broadcaster/1,premium/1;client-nonce={REDACTED_NONCE};color=#008000;display-name={REDACTED_CHANNEL_NAME};emotes=;first-msg=0;flags=;id=cc1c04b6-08de-45c1-9c79-6f2f62faecbb;mod=0;room-id={REDACTED_ROOM_ID};subscriber=0;tmi-sent-ts=1653760568213;turbo=0;user-id={REDACTED_ROOM_ID};user-type= :{REDACTED_CHANNEL_NAME}!{REDACTED_CHANNEL_NAME}@{REDACTED_CHANNEL_NAME}.tmi.twitch.tv PRIVMSG #{REDACTED_CHANNEL_NAME} :!ping' |
- 2022-05-28 19:56:08.5165 | Info  | BotChannelService_{REDACTED_CHANNEL_NAME} |  | '!ping' received |
- 2022-05-28 19:56:08.5165 | Info  | BotChannelService_{REDACTED_CHANNEL_NAME} |  | Trying so send message 'pong!' |
- 2022-05-28 19:56:14.6858 | Debug | BotChannelService_{REDACTED_CHANNEL_NAME} |  | Socket message: '@msg-id=no_permission :tmi.twitch.tv NOTICE #{REDACTED_CHANNEL_NAME} :You don't have permission to perform that action.
- ' |
- 2022-05-28 19:56:14.6858 | Info  | TwitchLib.Client.TwitchClient |  | [TwitchLib, 3.2.4.0] Received: @msg-id=no_permission :tmi.twitch.tv NOTICE #{REDACTED_CHANNEL_NAME} :You don't have permission to perform that action. |
- 2022-05-28 19:56:14.6858 | Info  | BotChannelService_{REDACTED_CHANNEL_NAME} |  | Client SendReceive: 'Received': '@msg-id=no_permission :tmi.twitch.tv NOTICE #{REDACTED_CHANNEL_NAME} :You don't have permission to perform that action.' |
- 2022-05-28 19:56:14.6858 | Warn  | BotChannelService_{REDACTED_CHANNEL_NAME} |  | No permission to do that |

**Comment by Syzuna** [comment]
That sounds like you only requested the chat:read scope so you are only allowed to read.
Try making a new token and add the chat:edit scope to the list of requested scopes

**Comment by MTrinkiesJr** [comment]
Yes i missed that previously and added the scope, but it don't work

**Comment by Mahsaap** [comment]
Have you tried to use the channel from the returned object of the event instead of hard-coded channel.

So something like e.channel.name

That may be wrong. Just off top my head.

**Comment by MTrinkiesJr** [comment]
Okay I fixed it, I needed to remove the connection in the channel where I'm connecting. Then created a new access token.
Thanks for your fast answer!

**Comment by Mahsaap** [comment]
Awesome 👍
