### ISSUE TITLE
Events terminate early?

### ISSUE THREAD

**Issue by NullNRG** [TwitchLib/TwitchLib.Client#193]
I can not get events to execute all the way through the method.
To elaborate:
When Client_OnConnected is called and triggered, it only ever executes the first line of code I have within method, then abruptly leaves the Client_OnConnected without executing the rest. NO matter what the code is, no matter which event, always leaves. As if the events do not have enough time to execute all the containing  code, and doesnt throw an error.

This is following the examples given on the main page TwitchLib page.

**Comment by Mahsaap** [comment]
I know your saying it's from the example code, but most the example code only has one line in the event already, can you so an example of your code? I don't understand why that is happening and would like to see an example of code that is doing this.

**Comment by Mahsaap** [comment]
![image](https://user-images.githubusercontent.com/13688718/175750753-6bc5d5fe-72a0-45bd-9612-a9112b44f218.png)
seems to be working for me

**Comment by NullNRG** [comment]
I Apologize, i should have given more information. The code is exactly as displayed for the TwitchLib.Client C# example, minus the Console.Writeline()'s, as i'm not making a console application. I'm am using TwitchLib.Client in a .Net MAUI project.

Any code I put in the Client_OnConnected or other events never trigger past the first line / statement, only the first line gets executed in the event, no matter if it's even just simple string or int variable assignments, the result is always not getting executed nor breakpoints reached, no output, no error, etc.
