### ISSUE TITLE
OnChannelStateChanged issues with Followers-only mode

### ISSUE THREAD

**Issue by laperie** [TwitchLib/TwitchLib.Client#207]
OnChannelStateChanged does not communicate to client app when the Followers-only mode is switched off: 
 as per [Twitch API spec](https://dev.twitch.tv/docs/irc/tags/#prototype-5) followers_only takes value -1 if the chat is not restricted. And value 0 means 'all followers'.   Yet, the '-1' value is ignored while parsing the IRC string:
Models/ChannelState.cs: 68
```
 case Tags.FollowersOnly:
                        if(int.TryParse(tagValue, out int minutes) && minutes > -1)
                        {
                            FollowersOnly = TimeSpan.FromMinutes(minutes);
                        }
                        break;
```
which means that OnChannelStateChanged will be called with FollowersOnly set to null which is erroneously interpreted as 'Followers Only mode switched off' in all cases when Tags.FollowersOnly is not present in IRC string.   

To  reproduce the problem:

1. Switch followers-only mode on to '0'
2. Switch emote-only mode on while followers-only mode is active
3. The response to (2) will not contain 'followers-only' and thus will be interpreted by the client as 'followers-only' mode is switched off. 

To solve the problem:
1. Introduce special value 'Followers-mode off' (I suggest TimeSpan.MinValue)
2. Assign this value to FollowersOnly if minutes =  -1
3. In the client application treat all values of FollowersOnly as TimeSpan.MinValue 'switched off'

**Comment by swiftyspiffy** [comment]
Should be fixed and in dev branch now.
