### ISSUE TITLE
ChatMessage.EmoteReplacedMessage should be populated based on ChatMessage.EmoteSet

### ISSUE THREAD

**Issue by nyxojaele** [TwitchLib/TwitchLib.Client#21]
Twitch chat doesn't blindly replace all occurrences of emote text with a graphic, for example:
`LUL "LUL"` will result in 
![image](https://user-images.githubusercontent.com/1314115/38287494-3320fdf0-3788-11e8-84d4-32399bead357.png)

However, TwitchLib will show that same line as 
![image](https://user-images.githubusercontent.com/1314115/38287610-d4c1beba-3788-11e8-9942-8993125ae9ff.png)

This happens despite the fact that in TwitchLib, the received ChatMessage.EmoteSet only shows a single replacement should happen. The source code shows that the EmoteSet seems to be completely ignored, and instead a regex is used.

**Comment by swiftyspiffy** [comment]
Will look into this Friday or Saturday. Might not be a simple fix.

**Comment by swiftyspiffy** [comment]
I was unable to look into it further on Friday or Saturday in April of 2018, but looking now. Still not fixed.

**Comment by swiftyspiffy** [comment]
This has been fixed in dev.
