### ISSUE TITLE
Refactor USERNOTICE state models like`Announcement`, `Subscriber`, etc.

### ISSUE THREAD

**Issue by neon-sunset** [TwitchLib/TwitchLib.Client#242]
These have a lot of state duplication causing really unfortunate patterns in the code due to passing flags and properties that share the same meaning/role yet exist in a duplicated and independent way.

This issue tracks the refactoring of that and also a @AoshiW idea of de-duplicating the parsing (which will interact with state aggregation above) e.g.:
```cs
abstract class UserNotice // better name
{
    //all tags that are same across all UserNotice commands
    public string HexColor { get; }
    public Dictionary<string, string>? UndocumentedTags { get; }

    protected UserNotice(IrcMessage message)
    {
        foreach (var tag in message.Tags)
        {
            switch (tag.Key)
            {
                case "color":
                    HexColor = tag.Value;
                    break;
                default:
                    if (!TrySet(tag))
                        (UndocumentedTags ??= new()).Add(tag.Key, tag.Value);
                    break;
            }
        }
    }

    protected abstract bool TrySet(KeyValuePair<string, string> tag);
}
class Announcement : UserNotice
{
    //tags that start with "msg-param"
    public string MsgParamColor { get; protected set; }

    public Announcement(IrcMessage message) : base(message)
    {
    }

    protected override bool TrySet(KeyValuePair<string, string> tag)
    {
        switch (tag.Key)
        {
            case "msg-param-color":
                MsgParamColor = tag.Value;
                break;
            default:
                return false;
        }
        return true;
    }
}
```

As for state aggregation, my idea is to make `IsModerator`, `IsBroadcaster`, etc. boolean flags into a dedicated `UserDetails` (or better name) struct which will expose these as properties yet hold them internally as a `[Flags]` enum. This will both improve object size and ease of use since the code will be consolidated and more compact.

**Comment by AoshiW** [comment]
Has anyone started working on this yet? If not, I'll start working on it.

**Comment by neon-sunset** [comment]
> Has anyone started working on this yet? If not, I'll start working on it.

I had this idea of how it's gonna look but busy right now, will happily participate in PRs you submit though.

**Comment by AoshiW** [comment]
I started working on it, but I ran into a few "problems":
- There's a model for [`ritual`](https://github.com/TwitchLib/TwitchLib.Client/blob/dev/TwitchLib.Client.Models/RitualNewChatter.cs) but it's not used anywhere and in my testing, I didn't even see such an event, should I delete it or overwrite it and create an event for it?
- should I do something about the "inconsistent" naming of models and their MsgId? Somewhere it doesn't matter (`ReSubscription = "resub"`) but somewhere else it's a problem (`ContinuedGiftedSubscription = "giftpaidupgrade"`) 
- do we want to keep the constructors/builders or can I delete it?

**Comment by neon-sunset** [comment]
> There's a model for [ritual](https://github.com/TwitchLib/TwitchLib.Client/blob/dev/TwitchLib.Client.Models/RitualNewChatter.cs) but it's not used anywhere and in my testing, I didn't even see such an event, should I delete it or rewrite it and create an event for it?

It might be worth doing this separately - i.e. have new structure first, then remove unused parts (unless this complicates the refactor). I'm not that familiar with Twitch API itself so maybe someone else has a better idea?

> should I do something about the "inconsistent" naming of models and their MsgId? Somewhere it doesn't matter (ReSubscription = "resub") but somewhere else it's a problem (ContinuedGiftedSubscription = "giftpaidupgrade")

You probably know best :) But roughly speaking it's naming in the official API > alternative naming that makes sense > other options, generally having different names for the same primitive is confusing, but it's hard to say anything without looking at a PR.

https://github.com/TwitchLib/TwitchLib.Client/blob/dev/TwitchLib.Client.Models/Builders/WhisperMessageBuilder.cs

> do we want to keep the constructors/builders or can I delete it?

Do you think it's a good idea to delete them? On builders, https://github.com/TwitchLib/TwitchLib.Client/blob/dev/TwitchLib.Client.Models/Builders/WhisperMessageBuilder.cs and the likes - these almost never have a reason to exist in C# code because they do nothing and "move away" the ownership of the "knowledge" about a particular type to a separate place for no benefit. But then again, your previous refactors were nice so just do what you think is best.

**Comment by AoshiW** [comment]
> It might be worth doing this separately - i.e. have new structure first, then remove unused parts (unless this complicates the refactor)

`ritual` is one of the models that must be rewritten so there is no reason to do it separately 
![image](https://github.com/TwitchLib/TwitchLib.Client/assets/48525283/31422c45-3a53-4045-8eb6-1137f7654619)

> You probably know best :) But roughly speaking it's naming in the official API > alternative naming that makes sense > other ...

well ...  I don't know what's best :D but I guess I'll leave it as it is and then someone else could create a readme where these "implementation details" will be written   

>Do you think it's a good idea to delete them?

I don't know... deleting constructors is probably not a good idea but deleting the builders might not be a problem. (but I'd still like to hear some other opinions)

**Comment by swiftyspiffy** [comment]
I believe this work was completed by @AoshiW .

**Comment by AoshiW** [comment]
this issue is not 100% resolved yet 
there's still this to do:
> As for state aggregation, my idea is to make IsModerator, IsBroadcaster, etc. boolean flags into a dedicated UserDetails (or better name) struct which will expose these as properties yet hold them internally as a [Flags] enum. This will both improve object size and ease of use since the code will be consolidated and more compact.

**Comment by AoshiW** [comment]
This issue is resolved and can be closed.
