### ISSUE TITLE
EmoteExtractor breaks on messages with emoji

### ISSUE THREAD

**Issue by Hampo** [TwitchLib/TwitchLib.Client#259]
Sent the message `One 😂 Two Kappa Three` in Twitch:
![Twitch Chat](https://img.proddy.xyz/Proddy/o9VlhEX.png)

Set a breakpoint on the first `Emote` in the `EmoteSet`:
![Emote](https://img.proddy.xyz/Proddy/xm0sK1p.png)

You can see the `emote.Name` is ` Kapp` instead of `Kappa`. Best guess is `EmoteExtractor` not respecting multi-byte characters, like emoji.

**Comment by Hampo** [comment]
Version tested on was `4.0.0-preview-bb8afa27cfa09f9d3c221969879b0adb43809afa`

**Comment by Syzuna** [comment]
Fixed #260
