### ISSUE TITLE
Login authentication failed

### ISSUE THREAD

**Issue by boffman** [TwitchLib/TwitchLib.Client#263]
HI, if I initialize the client with an old/expired access token, and get the OnIncorrectLogin callback, I want to refresh the token and redo the connect with the new access token. But it seems like the client is stuck in trying to reconnect over and over. Is there some way to handle this scenario? Calling Disconnect() in this situation gives an error also, and it keeps on trying, it seems. I also cannot call SetConnectionCredentials() with the new access token, since it's connected and that gives an error in that case.
Using TwitchLib.Client v3.3.1.

**Comment by Bukk94** [comment]
Disconnect problems is known issue of 3.x version. Try using the latest preview version of 4.0.0.

**Comment by boffman** [comment]
Thanks, I'll try that. 
..By the way, how to you clone the TwitchLib.Client repo, and also include cloning the correct corresponding version of TwitchLib.Communication?

**Comment by swiftyspiffy** [comment]
In general, the latest in Client's `dev` branch should work with the latest in Communication. Beyond that, there's not really hard linking. There's also not linking between commits to nuget releases AFAIK. Closing this.
