### ISSUE TITLE
Could Not Load File or Assembly

### ISSUE THREAD

**Issue by MadMikeGamerXL1** [TwitchLib/TwitchLib.Client#34]
I just installed this package, but every time I run the client, I get this error. I've tried updating my NuGet packages, and have also tried deleting the bin and obj folders; neither solutions work.
It will only run if I comment out everything to do with TwitchLib.Client. 

`Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)`

The code it seems to be failing on is the following: 

```
private TwitchClient client;

public void Connect()
{
        ConnectionCredentials credentials = new ConnectionCredentials("MadGamerBot", Auth);
            
        client = new TwitchClient();
            
        client.Initialize(credentials, "#itsmike");
            
        client.OnJoinedChannel += onJoinedChannel;
        client.OnMessageReceived += onMessageReceived;
        client.OnDisconnected += onDisconnected;
        client.OnConnected += onConnected;
        client.OnConnectionError += onConnectionError;
            
        client.Connect();
}
```

What's wrong here?

**Comment by swiftyspiffy** [comment]
I've seen this issue a couple times. Try adding `Microsoft.Extensions.Logging.Abstractions` package from NuGet and see if it works.

**Comment by Mahsaap** [comment]
If that is required we should add that to the dependencies list? Swift

**Comment by swiftyspiffy** [comment]
Honestly, I thought it was just an issue I was encountering. Will look into this more indepthly.

**Comment by MadMikeGamerXL1** [comment]
Glad to hear it's not just me! 
Thank you.
