### ISSUE TITLE
TwitchLib.Client/TwitchLib.Client/Events/OnRaidNotificationArgs.cs

### ISSUE THREAD

**Issue by Invariel** [TwitchLib/TwitchLib.Client#35]
Public instance variable RaidNotificaiton should probably have a different name, because that is a horrible misspelling.  I recognize that it would otherwise match the class name (which could be renamed BeingRaidedNotification, for example), but being misspelled like that makes me sad.

**Comment by madmaxXXL** [comment]
This is my first post and I can barely type help

**Comment by swiftyspiffy** [comment]
This looks to have been fixed at some point as it doesn't appear to exist anymore.
