### ISSUE TITLE
JoinedChannelManager Should be Case Insensitive

### ISSUE THREAD

**Issue by benrick** [TwitchLib/TwitchLib.Client#37]
The JoinedChannelManager needs to be case insensitive.

**Comment by swiftyspiffy** [comment]
So JoinedCHannelManager is a manager. Are you saying that GetJoinedChannel? That returns a JoinedChannel model. I'm probably missing something here.

**Comment by RRickkert** [comment]
Looks like this issue is fixed. Can't it be closed? @swiftyspiffy

**Comment by swiftyspiffy** [comment]
@RRickkert it can, thanks for the reminder
