### ISSUE TITLE
Client.OnMessageReceivedArgs not holding any emote data + other problem

### ISSUE THREAD

**Issue by swiftyspiffy** [TwitchLib/TwitchLib.Client#42]
_From @Kesiek on April 16, 2018 14:31_

Hello. As the title says, in 2.1 API version the Client.OnMessageReceivedArgs.EmotesSet is not holding any data, no matter what and how many emotes there is in message, it always returns 0.

And the second problem is that I'm always getting error when I'm trying to update channel title or game with TwitchAPI.Channels.v5.UpdateChannelAsync() method
Crash message:
`   Something went wrong during the request! Please try again later `

Here is link to stack trace to not overspam this post: [https://pastebin.com/fh5gBeCw](url)
And the code for method is:
       
        public async Task<string> ChangeStreamTitleAsync(string message)
        {
            try
            {
                var a = await twitchAPI.Streams.v5.GetStreamByUserAsync(userId);
                if (a.Stream == null)
                    return "offline";

                await twitchAPI.Channels.v5.UpdateChannelAsync(userId, message);
                return "updated";
            }
            catch (Exception ex)
            {
                DebugConsole.DisplayInDebugConsole(ex.StackTrace, error: true);
                DebugConsole.DisplayInDebugConsole(ex.Message, error: true);
                return "error";
            }
        }

_Copied from original issue: TwitchLib/TwitchLib#392_

**Comment by swiftyspiffy** [comment]
_From @Syzuna on April 16, 2018 15:2_

do you have the Api logging enabled to see the actual status code you got back? bcs if you got this exception message your status code didnt hit anything in the switch statemend we have.. so apparently no 400,401,404,422,500,502 or 504

**Comment by swiftyspiffy** [comment]
_From @Syzuna on April 16, 2018 15:3_

maybe a 503 from the api? bcs I just saw that we dont check for this

**Comment by swiftyspiffy** [comment]
_From @Kesiek on April 16, 2018 15:26_

No, I don't have the logging enabled. I will try to enable it and I will report back if I will get any result

**Comment by swiftyspiffy** [comment]
_From @Mahsaap on April 16, 2018 15:52_

removed comments for some reason i saw get by username

**Comment by swiftyspiffy** [comment]
_From @Kesiek on April 16, 2018 16:1_

@Mahsaap This is how I'm getting the channelId (for me its called userId)     
So it should work if I'm understanding this correctly

        public async Task GetUserId()
        {
            var uL = await twitchAPI.Users.v5.GetUserByNameAsync(Program.ChannelName);
            var userList = uL.Matches;

            if (userList == null || userList.Length == 0)
                userId = string.Empty;
            else
                userId = userList[0].Id.Trim();
        }

**Comment by swiftyspiffy** [comment]
_From @Mahsaap on April 16, 2018 16:9_

your fine, i just misread the call. i tend to do it alot sadly

**Comment by swiftyspiffy** [comment]
_From @Kesiek on April 16, 2018 16:54_

Alright, it took me way too long to figure out the loggin but here I have the result, 
info: TwitchLib.Api.TwitchAPI[0]
      Timestamp: 04/16/2018 18:51:21 Type: Request Method: PUT Resource: https://api.twitch.tv/kraken/channels/56159327 Content: { "channel": {"status": "Test title"} }
fail: TwitchLib.Api.TwitchAPI[0]
      Timestamp: 04/16/2018 18:51:22 Type: Response Resource: https://api.twitch.tv/kraken/channels/56159327 Statuscode: 403 Elapsed: 635 ms Content:       D?K

**Comment by swiftyspiffy** [comment]
_From @Kesiek on April 16, 2018 16:58_

And yes, I have the bot token for channel_editor

**Comment by swiftyspiffy** [comment]
_From @Syzuna on April 17, 2018 8:10_

Ok your bot has the channel_editor scope. I dont know if this is actually required but is the bot also registered as Editor of your stream in your Dashboard?

**Comment by swiftyspiffy** [comment]
_From @Kesiek on April 17, 2018 8:23_

Alright, I just checked it and no, bot wasn't registered as stream editor, but after adding it in there everything seems to work.
Thats one problem resolved.
Thank You.

**Comment by swiftyspiffy** [comment]
_From @Syzuna on April 17, 2018 12:11_

The emote thing is a little bit more intresting.. the emote parsing Code is most likely the oldest untouched Code in this libary. 
It was only a matter of time until other changes break it.
We still didnt find a good way to rewrite it yet but will look into it again

**Comment by swiftyspiffy** [comment]
_From @Kesiek on April 17, 2018 14:5_

Oh well.. I will just have to wait.
Thanks for help and have fun with fixing stuff!

**Comment by RRickkert** [comment]
I just noticed this issue. Not sure why no one was able to fix this sooner, but I guess the message not holding any emote data is fixed in my pull request #54

**Comment by RRickkert** [comment]
It might be good to move this to another issue / change the description, to make it more clear what issue still needs to be resolved. "+ other problem" in the title doesn't say much @swiftyspiffy

**Comment by Syzuna** [comment]
The other problem was already solved

**Comment by Syzuna** [comment]
so this can be closed I guess

**Comment by swiftyspiffy** [comment]
@Syzuna thanks for reminder
