### ISSUE TITLE
JoinChannel gets stuck if joining suspended account

### ISSUE THREAD

**Issue by Julusian** [TwitchLib/TwitchLib.Client#43]
At startup I am connecting to a bunch of channels, and the library gets stuck after trying to join a channel that has been suspended(more precisely renamed). The following is logged for the offending channel with nothing more occuring after that.
```
Received: @msg-id=msg_channel_suspended :tmi.twitch.tv NOTICE #scorpion1813 :This channel has been suspended.
Unaccounted for: @msg-id=msg_channel_suspended :tmi.twitch.tv NOTICE #scorpion1813 :This channel has been suspended.
```

The issue looks to be occuring because the lib only allows one JOIN to be inflight at a time and is waiting for a success response but an error is received instead

**Comment by swiftyspiffy** [comment]
Woah, I was not aware of this message. Interesting. We'll add a check for this.

**Comment by swiftyspiffy** [comment]
@Julusian if you want to give this a try again with the latest code, it should be fixed.

**Comment by Julusian** [comment]
Almost works. After #46 it works great :)

**Comment by swiftyspiffy** [comment]
Haha, oops. Thanks!

**Comment by swiftyspiffy** [comment]
A heads up, there seems to be a problem related to parsing with the joined channel count (suspended channel is being added to joined channels list). Looking into it
