### ISSUE TITLE
Add ChatMessage Id field

### ISSUE THREAD

**Issue by Julusian** [TwitchLib/TwitchLib.Client#44]
Would it be possible to expose the message Id on ChatMessage?
I am looking to run multiple instances of this library for reliability, so need to accurately identify messages across each instances to ensure they are only handled once. Time and contents isnt accurate enough I have found, so could really do with the id field to be available for this

Example IRC:
```
@badges=broadcaster/1,premium/1;color=#20569D;display-name=Julusian;emotes=;id=d67c6f6c-a7e1-4ada-b4f1-82b0da0622dc;mod=0;room-id=79110861;subscriber=0;tmi-sent-ts=1526757334890;turbo=0;user-id=79110861;user-type= :julusian!julusian@julusian.tmi.twitch.tv PRIVMSG #julusian :dd
```

**Comment by swiftyspiffy** [comment]
Yup, for some reason I thought we were already doing that, but I guess not. Will get a PR out for this and your previous problem.

**Comment by swiftyspiffy** [comment]
@Julusian should be available now.

**Comment by Julusian** [comment]
Thanks. All looks to be good now
