### ISSUE TITLE
Extension methods should require channel as their first parameter

### ISSUE THREAD

**Issue by swiftyspiffy** [TwitchLib/TwitchLib.Client#51]
Per the requirement for SendMessage, we should consider requiring the channel as the first parameter for various extension methods include TimeoutUser

**Comment by Syzuna** [comment]
I agree on that. I thought we changed them all already but semms like I was wrong

**Comment by RRickkert** [comment]
Looking at the extension method TimeoutUser, 1 of the methods already contains the possibility to provide a channel:
`public static void TimeoutUser(this ITwitchClient client, string channel, string viewer, TimeSpan duration, string message = "", bool dryRun = false)`

`public static void TimeoutUser(this ITwitchClient client, JoinedChannel channel, string viewer, TimeSpan duration, string message = "", bool dryRun = false)`

There is however, another method which doesn't require the channel as the first parameter:
`public static void TimeoutUser(this ITwitchClient client, string viewer, TimeSpan duration, string message = "", bool dryRun = false)`

Would you recommend removing the last method?

This also raises a question, why does the SendMessage method require a channel parameter? What was wrong with using an implementation as in the last TimeoutUser method? (Except for the fact that it doesn't provide any feedback if you're not connected to any channel)

**Comment by swiftyspiffy** [comment]
I had forgotten I intentially added an override method that doesn't accept a channel, and instead sends the message using the first JoinedChannel object in the JoinedChannels list. This kind of method is kind of contrary to the direction we've gone in requiring channel, and I think it's probably good practice to have the programmer explicitely state which channel they're sending the message (or in this case, the time out to).

Thoughts @RRickkert @LuckyNoS7evin @Syzuna ?

**Comment by Mahsaap** [comment]
Everything else is this way it would only make sense to continue

**Comment by LuckyNoS7evin** [comment]
Agree, the reason we went down the specification of channel on every request was due to "hidden functionality with no warnings" for example this picked JoinedChannels[0] which threw an exception of there was no joined channel. It also caused issues for those that do join multiple channels as you could not guarantee what channel is in [0].

That's my two cents though

**Comment by swiftyspiffy** [comment]
This has been fixed.
