### ISSUE TITLE
EmoteSet still empty

### ISSUE THREAD

**Issue by D3thw0lf** [TwitchLib/TwitchLib.Client#67]
I tried to get emotes to work (again) but it seems like the ChatClient is not getting any of them (even after latest fixes in #54 )

So what I've tried was to get the number of emotes in a message in normal Chat and Whispers. The result was that whispers EmoteSet is working and normal chat still ends in "0".

Code I've tried:
```c
public void WhisperReceived(object sender, OnWhisperReceivedArgs e)
{
   Console.WriteLine($"EMOTE COUNT (WHISPER): {e.WhisperMessage.EmoteSet.Emotes.Count}");
}
```

```c
public void ChatMessageReceived(object sender, OnMessageReceivedArgs e)
{
   Console.WriteLine($"EMOTE COUNT (CHAT): {e.ChatMessage.EmoteSet.Emotes.Count}");
}
```

Using TwitchLib 2.1.5 (latest NuGet)
Using TwitchClient 2.1.4 (latest NuGet)
Using .NET Framework 4.6.2

I did not tried any console application yet but maybe someone can report back if I missed something.

**Comment by prom3theu5** [comment]
I don't think those fixes are actually in the nuget release yet
Looking at it - it's been a month since we had a new version out

**Comment by D3thw0lf** [comment]
Ah that's good to know. Then I didn't say anything and this can get closed ^^' ... Thank you for enlightening me. :)
