### ISSUE TITLE
"none" is logged

### ISSUE THREAD

**Issue by DwaigonAumer** [TwitchLib/TwitchLib.Client#8]
Hey!

I was wondering why "none" showed up in my log a couple of times and i started searching for it, eventually i found it here: https://github.com/TwitchLib/TwitchLib.Client/blob/d7829c879228889746a45cdbc8443bf7529b97f7/TwitchLib.Client/TwitchClient.cs#L1005

Is there a specific reason why it logged "none" instead of just nothing, was this for debugging purposses perhaps?

**Comment by swiftyspiffy** [comment]
Does look like it was added for debugging a little bit ago: https://github.com/TwitchLib/TwitchLib/blame/1f7ed8c2509faa9f4f49d9c1617026616e9209cd/TwitchLib.Client/TwitchClient.cs#L1004

I'll go ahead and remove it.

**Comment by swiftyspiffy** [comment]
Should be good now, sorry about that :)

**Comment by DwaigonAumer** [comment]
No worries, thanks for removing!
