### ISSUE TITLE
No possibility to detect a disabled "followers-only" state?

### ISSUE THREAD

**Issue by jzeyer** [TwitchLib/TwitchLib.Client#88]
Is there any way to detect when `followers-only` mode is disabled? As soon as the RoomState-Tag returns -1 once it is disabled, the timespan for that mode will be set to 0. However, it's also 0 if the mode is active with a duration of 0 (all followers are allowed to write). https://github.com/TwitchLib/TwitchLib.Client/blob/a1e90e3b87f4876a0293a4833cf05389a9010447/TwitchLib.Client.Models/ChannelState.cs#L62

**Comment by TETYYS** [comment]
This is a bug, I think preferred solution would be making `FollowersOnly` field nullable or making it an `int`, just like Twitch sends it.

**Comment by Mahsaap** [comment]
Twitch sends json which is string and has to be parsed.

**Comment by TETYYS** [comment]
And the parsed field is integer, in minutes.

**Comment by Mahsaap** [comment]
I think we are not seeing eye to eye I'll let someone that knows more figure it out. O7 I do recall this coming up before on something similar

**Comment by swiftyspiffy** [comment]
Just getting around to this. I think it's safe to assume this value is an integer, but I'll have an additional check to make sure it's numeric, or set it to -1.

**Comment by swiftyspiffy** [comment]
This is in dev now: https://github.com/TwitchLib/TwitchLib.Client/commit/a9a8c85f8af57e868d9b3f223af8cf9f0ee2d281

Feel free to reopen if it's not fixed. Will target a stable release in a few weeks. Use dev if you want it now :)
