### ISSUE TITLE
Mismatched data types on various subscribers event args

### ISSUE THREAD

**Issue by SeeingBlue** [TwitchLib/TwitchLib.Client#90]
`OnNewSubscriberArg`s & `OnReSubscriberArgs` badges are `List(of KeyPairValue(of string, string)` but `OnGiftedSubscriptionArgs`, `OnAnonGiftedSubscriptionArgs`, & `OnCommunitySubscriptionArgs` badges are strings.

`OnNewSubscriberArg`s & `OnReSubscriberArgs` colors are `Color` but `OnGiftedSubscriptionArgs`, `OnAnonGiftedSubscriptionArgs`, & `OnCommunitySubscriptionArgs` colors are strings.

`OnNewSubscriberArg`s & `OnReSubscriberArgs` Emotes are called `EmoteSet` but `OnGiftedSubscriptionArgs`, `OnAnonGiftedSubscriptionArgs`, & `OnCommunitySubscriptionArgs` emotes are called Emotes.

**Comment by Syzuna** [comment]
This should be fixed for quite some time already. 
going ahead and close this issue.
