### ISSUE TITLE
Events considered as Fields in VB.NET

### ISSUE THREAD

**Issue by SeeingBlue** [TwitchLib/TwitchLib.Client#91]
![image](https://user-images.githubusercontent.com/7357172/52156931-79dd4580-2659-11e9-872b-598d60812045.png)

 The above events are considered fields in VB.NET. See below.

![image](https://user-images.githubusercontent.com/7357172/52156953-a7c28a00-2659-11e9-81fe-0bdb96d8f170.png)

**Comment by Mahsaap** [comment]
#89

**Comment by swiftyspiffy** [comment]
All events have the event keyword now, in the latest stable release. Sorry about that!
