### ISSUE TITLE
Question concerning Community Gift Subs

### ISSUE THREAD

**Issue by BubbaSWalter** [TwitchLib/TwitchLib.Client#93]
IS there a way to see all the recipients of Community giftsubs?

**Comment by Mahsaap** [comment]
I think you just get gift notification and then use that count for the next number of subs.

**Comment by Syzuna** [comment]
Twitch sadly does not provide them as a batch so you have to look which ones belong to a sub bomb yourself

**Comment by swiftyspiffy** [comment]
As @Mahsaap and @Syzuna have previously stated, we can only work what Twitch makes available to us :(
