### ISSUE TITLE
C# Nuget TwitchLib.Client.Models 1.1.0 - Cannot find AnonGiftSubscript reference.

### ISSUE THREAD

**Issue by karminea** [TwitchLib/TwitchLib.Client#95]
I downloaded TwichLib.Client from nuget.
but TwitchLib.Client.Models.AnonGiftSubscription is missing from the nuget version.

![twitchlib](https://user-images.githubusercontent.com/8109159/53460234-c7de4100-3a7f-11e9-9d0a-ad2062b89d27.png)
![twitchlib2](https://user-images.githubusercontent.com/8109159/53460235-c7de4100-3a7f-11e9-8f03-f9f11c84b3af.png)
![twitchlib3](https://user-images.githubusercontent.com/8109159/53460237-c876d780-3a7f-11e9-8357-ada59de006ca.png)

**Comment by Mahsaap** [comment]
In progress of update. The nuget version model is mismatch for latest

**Comment by swiftyspiffy** [comment]
This should be resolved with the latest stable release. Please reopen if it is not. Thanks!
